export interface Tours {
    id?:string,
    Booked?:string,
    Categories?:string,
    City?:string,
    Date?:string,
    Image?:string,
    OldPrice?:string,
    Price?:string,
    Rate?:string,
    Review?:string,
    Section?:string,
    Title?:string,
    TourDiscount?:string,
    TourSectionInner?:string,
    Distance?: number,
    SubCategories?:string,
    TitleAr?: string,
    BookedAr?: number,
    CityAr?:string
    DateAr?: string,
    DescriptionAr?: string,
    PriceAr?: string,
    RateAr?: number,
    SectionAr?: string,
    OldPriceAr?: string,
    DistanceAr?: string,
    ReviewAr?: string,
    

}
